version: '3'
services:
  game-dev:
    build: .
    volumes:
      - .:/app
    environment:
      - DISPLAY=host.docker.internal:0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true